version: '3.8'
networks:
  line_net:
    driver: overlay
    external: true
services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - line_net

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
    networks:
      - line_net

volumes:
  ollama:
  mysql_data: